In [7]:
import scanpy as sc
import torch
import numpy as np


In [2]:
from torch import pca_lowrank

In [3]:
DATA_PATH = '/om/group/abugoot/Projects/Omnicell_datasets/essential_gene_knockouts_raw/essential_gene_knockouts_raw.h5ad'



with open(DATA_PATH, 'rb') as f:
    adata = sc.read_h5ad(f)


adata


AnnData object with n_obs × n_vars = 966728 × 11907
    obs: 'gem_group', 'gene', 'gene_id', 'transcript', 'gene_transcript', 'sgID_AB', 'mitopercent', 'UMI_count', 'z_gemgroup_UMI', 'cell_type', 'core_scale_factor', 'core_adjusted_UMI_count'

array([[0., 0., 0., ..., 1., 3., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 2., 0.]], dtype=float32)

In [11]:
pca_lowrank(torch.from_numpy(adata.X.toarray()))

(tensor([[ 3.7157e-04, -2.0009e-04,  2.7075e-04,  1.0168e-03,  1.5560e-04,
          -8.5922e-04],
         [ 7.6059e-04,  2.1687e-05, -8.3695e-05,  1.0211e-03,  2.4822e-06,
          -3.3941e-04],
         [ 6.7349e-04, -4.3709e-05,  9.1500e-05,  7.1605e-04, -1.7292e-04,
          -1.0218e-03],
         ...,
         [ 8.4028e-04, -1.5283e-04, -4.4769e-04, -1.6855e-04, -6.6013e-04,
          -2.3413e-05],
         [ 7.4332e-04, -4.6964e-04, -5.9111e-04,  3.0463e-05, -7.9281e-04,
           3.0992e-04],
         [ 1.2229e-04, -1.3748e-03, -4.4331e-04, -1.9899e-04, -9.7574e-04,
           8.7259e-05]]),
 tensor([376021.5312, 169124.7969, 139967.1406,  99020.2656,  87784.3125,
          67932.1406]),
 tensor([[-2.1886e-04, -1.1861e-03, -2.6686e-04, -2.2818e-04, -7.9104e-05,
          -9.6608e-04],
         [-1.5310e-03,  2.4152e-03, -4.3385e-03,  5.5596e-04, -2.6581e-04,
          -1.3833e-03],
         [-5.9712e-03,  1.1081e-02, -2.0469e-02, -2.7308e-03,  4.4445e-03,
          -5.1295e-