In [14]:
import scanpy as sc
import sys
import os

sys.path.append('..')  # Add parent directory to Python path
import numpy as np
import scipy 

In [15]:
adata = sc.read("/orcd/data/omarabu/001/Omnicell_datasets/repogle_k562_essential_raw/K562_essential_raw_singlecell_01.h5ad")


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [16]:
X_sparse = scipy.sparse.csc_matrix(adata.X)

In [17]:
X_sparse

<310385x8563 sparse matrix of type '<class 'numpy.float32'>'
	with 1121681215 stored elements in Compressed Sparse Column format>

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 1., 1., ..., 1., 0., 0.],
       ...,
       [0., 1., 4., ..., 0., 0., 0.],
       [0., 1., 5., ..., 1., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [8]:
X_sparse.toarray()

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 1., 1., ..., 1., 0., 0.],
       ...,
       [0., 1., 4., ..., 0., 0., 0.],
       [0., 1., 5., ..., 1., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [18]:
adata.X = X_sparse
adata.write("/orcd/data/omarabu/001/Omnicell_datasets/repogle_k562_essential_raw/K562_essential_raw_singlecell_01-temp.h5ad")